# Generated by Django 5.2.8 on 2025-11-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_bans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pin_thread', 'Pin Thread'), ('unpin_thread', 'Unpin Thread'), ('lock_thread', 'Lock Thread'), ('unlock_thread', 'Unlock Thread'), ('delete_thread', 'Delete Thread'), ('delete_reply', 'Delete Reply'), ('add_moderator', 'Add Moderator'), ('remove_moderator', 'Remove Moderator'), ('ban_user', 'Ban User'), ('unban_user', 'Unban User')], max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='groups.group')),
            ],
            options={
                'db_table': 'moderation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
