# Generated by Django 5.2.8 on 2025-11-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0002_initial'),
        ('groups', '0002_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='forums.reply'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs_as_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='forums.thread'),
        ),
        migrations.AddField(
            model_name='userban',
            name='banned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userban',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to='groups.group'),
        ),
        migrations.AddField(
            model_name='userban',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_3fcf45_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['group', '-created_at'], name='moderation__group_i_a5be34_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['action'], name='moderation__action_4ef591_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_global'], name='user_bans_user_id_3393ac_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['group'], name='user_bans_group_i_cf28f8_idx'),
        ),
    ]
