labels:
  - name: enhancement
    color: '0e8a16'
    description: New feature or request
  - name: area:infra
    color: '5319e7'
    description: Infrastructure related work
  - name: priority:P1
    color: 'b60205'
    description: High priority
