# Generated by Django 5.2.8 on 2025-11-16 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='groups.group'),
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forums.thread'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['group', '-pinned', '-created_at'], name='threads_group_i_db7e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['author'], name='threads_author__e11ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['thread', 'created_at'], name='replies_thread__a276b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['author'], name='replies_author__aff5df_idx'),
        ),
    ]
