# Generated by Django 5.2.8 on 2025-11-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_univers_ddd1bc_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_verific_ccfceb_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="blocked_users",
        ),
        migrations.RemoveField(
            model_name="user",
            name="onboarding_completed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="privacy_settings",
        ),
        migrations.RemoveField(
            model_name="user",
            name="university_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verified_at",
        ),
    ]
